### PR TITLE
Improved Docs

### PR DESCRIPTION
**Pull request by ktzsid10**

### CODE REVIEW

**Comment by faizmalkani** [comment]
Invalid

**Comment by ktzsid10** [comment]
May I know the reason why.?

cuz it's not like you are losing anything..?

**Comment by faizmalkani** [comment]
Please make meaningful contributions if you want to participate in Hacktoberfest, not just README edits where you add one space and expect a PR to be merged

**Comment by ktzsid10** [comment]
I'm really sorry I didn't see that..

In many I have improved the codings too.

I thought I did codings for every repository.

Sorry for the inconvenience.!
Hope you understand.!

**Pull request closed without merging**
